name: Run NTUST Bulletin 2 everyday at 8 pm (UTC+8)

on:
  schedule:
    - cron:  '0 12 * * *' # 8 pm (UTC+8)
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run NTUST Bulletin 2
      env:
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        RECIPIENT: ${{ vars.RECIPIENT }}
        SKIP_DATE_CHECK: ${{ vars.SKIP_DATE_CHECK }}
      run: python main.py
